# Generated by Django 3.1.7 on 2022-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('age', models.IntegerField(default=None, null=True)),
                ('income', models.IntegerField(default=None, null=True)),
                ('address', models.TextField(default='')),
                ('registration_number', models.TextField(default='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_married', models.BooleanField()),
            ],
        ),
    ]
