# Generated by Django 3.1.7 on 2022-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
